version: '3.8'
services:
    database:
        image: "postgres"
        container_name: biologia_db
        env_file:
            - .env.postgres
        volumes:
            - biologia_database-data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    api:
        container_name: biologia_api
        restart: always
        build:
          context: .
          dockerfile: ./Dockerfile
        depends_on:
            - database
        volumes:
            - .:/var/www/app/


    composer:
        container_name: biologia_composer
        image: composer:2.0
        stdin_open: true
        command: ["composer", "install"]
        volumes:
            - .:/app

    nginx:
        image: nginx:1.19
        container_name: biologia_nginx
        ports:
            - '127.0.0.1:8081:80'
        volumes:
            - .:/var/www/app/
            - ./etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
        depends_on:
            - api

volumes:
    biologia_database-data:
